export const data = [
  {
    id: 1,
    authorAvatar: "./img/avatars/linakostenko.jpg",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Test",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 2,
    authorAvatar: "./img/avatars/vasylsymonenko.jpg",
    author: "Василь Симоненко",
    username: "vasylsymonenko",
    content:
      "Можна все на світі вибирати, сину <br>Вибрати не можна тільки Батьківщину...",
    date: "04-23-1958",
    contentImg: "",
    likes: 542,
    retweets: 42,
    comments: 108,
  },
  {
    id: 3,
    authorAvatar: "./img/avatars/chornovil.jpg",
    author: "В’ячеслав Чорновіл",
    username: "chornovil",
    content:
      "Немає в нас бандерівців та москалів, східних і західних. Всі ми — народ України.",
    date: "02-04-1985",
    contentImg: "",
    likes: 4340,
    retweets: 430,
    comments: 173,
  },
  {
    id: 4,
    authorAvatar: "./img/avatars/vasyl_stus.jpg",
    author: "Василь Стус",
    username: "vasyl_stus",
    content:
      "Завжди любити, щоб завжди помилятися. Але — завжди любити. І відтак існувати, а існувати — це помилятися.",
    date: "07-17-1959",
    contentImg: "",
    likes: 5312,
    retweets: 650,
    comments: 238,
  },
  {
    id: 5,
    authorAvatar: "./img/avatars/Valerii_Markus.jpg",
    author: "Валерій Маркус",
    username: "Valerii_Markus",
    content: "Порошенко",
    date: "06-23-2022",
    contentImg: "",
    likes: 8423,
    retweets: 1341,
    comments: 3214,
  },
];
