export const data = [
  {
    id: 1,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 2,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 3,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 4,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 5,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 6,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 7,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
  {
    id: 8,
    authorAvatar: "",
    author: "Ліна Костенко",
    username: "linakostenko",
    content: "Все наше життя, це чекання найгіршого і надія на краще.",
    date: "12-04-1978",
    contentImg: "",
    likes: 23,
    retweets: 69,
    comments: 12,
  },
];
